# Generated by Django 5.1.1 on 2024-09-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='doctors',
            new_name='Doctor',
        ),
    ]
